name       : speedtest-cli
version    : 0.3.2
release    : 1
source     :
    - https://github.com/sivel/speedtest-cli/archive/v0.3.2.tar.gz : 54e55252ffa3c10ecbd5e23b08b01a42e149db3977ac4186f6bdf16b04d79511
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
