name       : speedtest-cli
version    : 2.1.3
release    : 15
source     :
    - https://github.com/sivel/speedtest-cli/archive/refs/tags/v2.1.3.tar.gz : 45e3ca21c3ce3c339646100de18db8a26a27d240c29f1c9e07b6c13995a969be
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
setup      : |
    %python3_setup
install    : |
    %python3_install
