name       : speedtest-cli
version    : 2.1.1
release    : 10
source     :
    - https://github.com/sivel/speedtest-cli/archive/v2.1.1.tar.gz : 433675c19bd40c059da5d98c512874742405e8185afed47f8aa11a02ac61aa06
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
setup      : |
    %python3_setup
install    : |
    %python3_install
