name       : speedtest-cli
version    : 2.0.2
release    : 9
source     :
    - https://github.com/sivel/speedtest-cli/archive/v2.0.2.tar.gz : 5e22f2dcce1c9020f33faf559b22727483f022008a2912b85d573e578374b6a0
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
setup      : |
    %python3_setup
install    : |
    %python3_install
