name       : speedtest-cli
version    : 1.0.7
release    : 7
source     :
    - https://github.com/sivel/speedtest-cli/archive/v1.0.7.tar.gz : 3853bb7a3d16f686441d0d10ebbfc1fd49e974ecf17248ce03456ad4ef2478b9
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
