name       : speedtest-cli
version    : 0.3.4
release    : 3
source     :
    - https://github.com/sivel/speedtest-cli/archive/v0.3.4.tar.gz : e50646e245ea3c80c9653a532db0dbaef72f1c439330bcc22c381074c17b719d
license    : Apache-2.0
component  : network.util
summary    : Command line interface for testing internet bandwidth using speedtest.net
description: |
    Command line interface for testing internet bandwidth using speedtest.net
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
